#!/bin/bash

PI="rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18 rpi19 rpi20"

array=$@

if [ ${#array[0]} = 0 ]
then
        array=$PI
fi

for x in $array;
do
        ping -c 1 -W 10 $x >&-
        if [ $? = 0 ]
        then
                echo $x "is alive"
        else
                echo $x "is dead"
        fi
done

exit 0
